export default {
  products: [
    {
      _id: '1',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '../images/d1.jpg',
      price: 11,
      brand: 'Nike',
      rating: 3.5,
      numReviews: 10,
      countInStock: 3,
    }, {
      _id: '2',
      name: 'Slim Shirt',
      category: 'Shirts',
      image: '../images/d1.jpg',
      price: 44,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 4,
    },
    {
      _id: '3',
      name: 'Slim Shirt',
      category: 'Pants',
      image: '../images/d1.jpg',
      price: 33,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 2,
    },
    {
      _id: '4',
      name: 'Slim Shirt',
      category: 'Pants',
      image: '../images/d1.jpg',
      price: 33,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 2,
    },
    {
      _id: '5',
      name: 'Slim Shirt',
      category: 'Pants',
      image: '../images/d1.jpg',
      price: 33,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 12,
    },
    {
      _id: '6',
      name: 'Slim Shirt',
      category: 'Pants',
      image: '../images/d1.jpg',
      price: 33,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 33,
    },
    {
      _id: '7',
      name: 'Slim Shirt',
      category: 'Pants',
      image: '../images/d1.jpg',
      price: 33,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 22,
    },
    {
      _id: '8',
      name: 'Slim Shirt',
      category: 'Pants',
      image: '../images/d1.jpg',
      price: 33,
      brand: 'Nike',
      rating: 2.5,
      numReviews: 10,
      countInStock: 6,
    },
  ]
}